server:
  port: 7020
  tomcat:
    maxThreads: 400
    minSpareThreads : 400
    maxConnections: 400
    acceptCount: 400

zuul:
  host:
    maxTotalConnections: 400
    maxPerRouteConnections: 400
    connect-timeout-millis: 8000
    socket-timeout-millis: 10000
  routes:
    api-zull:
      path: /**
      url: http://10.1.1.146:9000/

jmx:
  rmi:
    port: 17020

